spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    open:
      url:  jdbc:postgresql://127.0.0.1:5432/open
      username: open
      password: 123456789
      driver-class-name: org.postgresql.Driver