spring:
  data:
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      password: Cr4gs54ZXKJoVFYBV5J
      timeout: 3000
      connectTimeout: 10000
      clientName: w2-server
#      cluster:
#        nodes:
#      sentinel:
#        master:
#        nodes:
      ssl:
        enabled: false
