spring:
  data:
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      password: Cr4gs54ZXKJoVFYBV5J
      timeout: 3000
      connectTimeout: 10000
      clientName: w2-server
#      cluster:
#        nodes:
#      sentinel:
#        master:
#        nodes:
      ssl:
        enabled: false
#cosid:
#  namespace: ${spring.application.name}
#  machine:
#    enabled: true # 可选，当需要使用雪花算法时，需要设置为 true
#    distributor:
#      type: redis
#  generator:
#    enabled: true