spring:
  data:
    redis:
      database: 0
      host: localhost
      port: 6379
      password: null
      timeout: 3000
      connectTimeout: 10000
      clientName: w2-server
#      cluster:
#        nodes:
#      sentinel:
#        master:
#        nodes:
      ssl:
        enabled: false